### ISSUE TITLE
咨询下google fonts原理

### ISSUE THREAD

**Issue by littleCareless** [fate-lovely/google-font-downloader#1]
https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@300;400;500;700&display=swap
如下如所示，想请问一下为什么同一个字体同一个大小有这么多种字体woff2文件？到底哪个是使用的。
因为在前端开发的时候，我似乎只是导入一个woff2文件。
![image](https://user-images.githubusercontent.com/47601009/216201052-458976d1-ec2b-413c-9292-b3d4f09e1c3e.png)

**Comment by cj1128** [comment]
注意看 `unicode-range` 参数，字体根据字符的范围被切割成了多份，这样用不到的字符对应的那部分字体可以不用下载。

https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/unicode-range
